
SECTION_1 : ** Environment setup and data cleaning **

In [ ]:
import pandas as pd
housing_data = pd.read_csv('/content/drive/MyDrive/datasets/HousingDataset.csv', engine='python')
housing_data.head()

,Unnamed: 0,id,ad_type,start_date,end_date,created_on,lat,lon,l1,l2,...,bathrooms,surface_total,surface_covered,price,currency,price_period,title,description,property_type,operation_type
0,107397,YhXDVa/KIlF7EjJMulHiyA==,Propiedad,2020-03-26,2020-04-08,2020-03-26,-34.562465,-58.465079,Argentina,Capital Federal,...,2.0,NaN,NaN,220000.0,USD,NaN,OPPEL | Departamento en Venta | Cod: 29583,DEPARTAMENTO EN VENTA / ALQUILER | BELGRANO ...,Departamento,Venta
1,918839,jHxD7psAg4+AC07T3sognw==,Propiedad,2020-03-08,2020-03-09,2020-03-08,-37.999235,-57.553724,Argentina,Buenos Aires Costa Atlántica,...,1.0,NaN,NaN,155000.0,USD,NaN,2 AMBIENTES A ESTRENAR CON COCHERA,2 AMBIENTES CON BALCON Y PARRILLA. COCHERALIV...,Otro,Venta
2,204435,IYPdaIGi5Obo4eLzwUY+LA==,Propiedad,2020-10-26,2021-02-03,2020-10-26,-34.453307,-58.649410,Argentina,Bs.As. G.B.A. Zona Norte,...,3.0,900.0,310.0,480000.0,USD,Mensual,"Casa en Venta, Barrio Sta. Barbara","Casa racionalista en tres plantas, con espacio...",Casa,Venta
3,699972,Cc8bVzOhRcPnAYS++8oyMg==,Propiedad,2020-01-07,2020-01-07,2020-01-07,-31.635173,-60.716072,Argentina,Santa Fe,...,4.0,NaN,NaN,34000.0,ARS,Mensual,"Casa en Alquiler en Constituyentes, Santa fe $...",ALQUILER DE CASA DE 3 / 4 DORMITORIOS EN ZONA ...,Casa,Alquiler
4,66130,83DDzQ7686eLxOi9sQNJVA==,Propiedad,2020-05-13,2020-05-17,2020-05-13,NaN,NaN,Argentina,Santa Fe,...,2.0,200.0,200.0,20000.0,ARS,NaN,Laprida 1418,Laprida 1418 - KP27922 - - Aviso publicado po...,Casa,Alquiler

In [ ]:
housing_data.shape # we can see that we have 500027 rows and 26 columns.

(500027, 26)

In [ ]:
housing_data.info() # We have 17 columns object datatypes and 9 columns float64 datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500027 entries, 0 to 500026
Data columns (total 26 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Unnamed: 0       500027 non-null  object
 1   id               500027 non-null  object
 2   ad_type          500027 non-null  object
 3   start_date       500000 non-null  object
 4   end_date         500000 non-null  object
 5   created_on       500000 non-null  object
 6   lat              424515 non-null  float64
 7   lon              424065 non-null  float64
 8   l1               500000 non-null  object
 9   l2               500000 non-null  object
 10  l3               473344 non-null  object
 11  l4               119679 non-null  object
 12  l5               2498 non-null    object
 13  l6               0 non-null       float64
 14  rooms            262826 non-null  float64
 15  bedrooms         232669 non-null  float64
 16  bathrooms        388149 non-null  float64
 17  surface_total    189727 non-null  float64
 18  surface_covered  190695 non-null  float64
 19  price            481746 non-null  float64
 20  currency         481066 non-null  object
 21  price_period     181438 non-null  object
 22  title            500000 non-null  object
 23  description      499986 non-null  object
 24  property_type    499973 non-null  object
 25  operation_type   499973 non-null  object
dtypes: float64(9), object(17)
memory usage: 99.2+ MB

In [ ]:
housing_data.describe() # we are describing the dataset just to check the satistical observations such as mean, median, std and so on

,lat,lon,l6,rooms,bedrooms,bathrooms,surface_total,surface_covered,price
count,424515.000000,424065.000000,0.0,262826.000000,232669.000000,388149.000000,189727.000000,1.906950e+05,4.817460e+05
mean,-34.789084,-59.251769,NaN,2.857526,2.107277,1.710135,518.547792,1.170599e+04,3.220869e+05
std,2.945689,2.631140,NaN,1.677232,2.812046,1.080167,4417.012783,4.917869e+06,6.642452e+06
min,-54.841484,-111.717740,NaN,1.000000,-16.000000,1.000000,-136.000000,-1.300000e+02,0.000000e+00
25%,-34.919437,-58.742520,NaN,2.000000,1.000000,1.000000,50.000000,4.500000e+01,4.200000e+04
50%,-34.611225,-58.448355,NaN,3.000000,2.000000,1.000000,94.000000,7.600000e+01,9.800000e+04
75%,-34.457955,-58.172766,NaN,4.000000,3.000000,2.000000,253.000000,1.640000e+02,2.100000e+05
max,43.318334,-1.981231,NaN,40.000000,900.000000,20.000000,200000.000000,2.147484e+09,3.100000e+09

In [ ]:
housing_data.isna().sum()/len(housing_data)*100 # as we can see that we have a lot of null values in columns such as l6,lat,lon and so on...

Unnamed: 0           0.000000
id                   0.000000
ad_type              0.000000
start_date           0.005400
end_date             0.005400
created_on           0.005400
lat                 15.101585
lon                 15.191580
l1                   0.005400
l2                   0.005400
l3                   5.336312
l4                  76.065492
l5                  99.500427
l6                 100.000000
rooms               47.437638
bedrooms            53.468713
bathrooms           22.374392
surface_total       62.056649
surface_covered     61.863059
price                3.656003
currency             3.791995
price_period        63.714359
title                0.005400
description          0.008200
property_type        0.010799
operation_type       0.010799
dtype: float64

In [ ]:
#Identify and remove the following columns:
#a. ad_type
#b. title
#c. description
#d. l4
#e. l5
#f. l6

In [ ]:
# based on the above instructions I am removing those columns from the dataset.

housing_data.drop(["ad_type","title","description","l4","l5","l6"],axis=1,inplace=True)

In [ ]:
# removing "unnamed: 0" column because you havent mentioned to add in the property_details or property_price_details

housing_data.drop(["Unnamed: 0"],axis=1,inplace=True)

In [ ]:
housing_data.shape # after removing the columns we have 20 columns in the dataset

(500027, 19)

In [ ]:
#Investigate and discard all rows that contain Null values in any of these fields:
#a. lon
#b. lat
#c. price_period
#d. bedrooms
#e. surface_total
#f. rooms
#g. price
#h. surface_covered

In [ ]:
# as per the above instructions i am removing the null values from mentioned columns.

housing_data.dropna(subset=["lat","lon","price_period","bedrooms","surface_total","rooms","price","surface_covered"],inplace=True)

In [ ]:
property_details = housing_data[["id","start_date","end_date","created_on","lat","lon","l1","l2","l3","rooms","bedrooms","bathrooms","surface_total","surface_covered"]]
property_price_details = housing_data[["id","price","currency","price_period","property_type","operation_type"]]

SECTION_2 : ** Data Analysis **

In [ ]:
import sqlite3

# connecting to an SQLite database
conn = sqlite3.connect('Housing_data.db')

# Saving 'property_details' DataFrame as a table in the database
property_details.to_sql('property_details', conn, if_exists='replace', index=False)

# Saving 'property_price_details' DataFrame as a table in the database
property_price_details.to_sql('property_price_details', conn, if_exists='replace', index=False)

43436

In [ ]:
from sqlalchemy import create_engine,text
import pandas as pd

# Create a database connection
engine = create_engine('sqlite:///Housing_data.db')

# Executing sql query and storing it in dataframe
# question 1 : Retrieve properties that have a price greater than 1 million and are located in "Estados Unidos" (l1).

problem_1 ="SELECT pd.id, ppd.property_type, pd.l1, ppd.price FROM property_details pd INNER JOIN property_price_details ppd ON pd.id = ppd.id WHERE pd.l1 = 'Estados Unidos' AND ppd.price > 1000000;"

conn_sql1 = pd.DataFrame(engine.connect().execute(text(problem_1)))

conn_sql1

                         id property_type              l1      price
0  jia0r061K3bw5GPCHag4/Q==  Departamento  Estados Unidos  1175000.0
1  swvA3wM1Df6lwOBx4ciKJg==  Departamento  Estados Unidos  2595000.0
2  4tMKIwmJObpzvXuT/fFPnQ==  Departamento  Estados Unidos  3000000.0
3  7Aa4z2SWO2mp+P/JXdTmsA==  Departamento  Estados Unidos  3000000.0
4  fAv1rqL0LHZOiqDaDNwrzA==  Departamento  Estados Unidos  3000000.0

In [ ]:
# question 2 : Categorize properties based on their surface area as 'Small' if it's less than 50 square meters, 'Medium' if it's
#between 50 and 100 square meters, and 'Large' if it's greater than 100 square meters:

problem_2 = """SELECT *,
  CASE
    WHEN surface_total < 50 THEN 'Small'
    WHEN surface_total >= 50 AND surface_total <= 100 THEN 'Medium'
    WHEN surface_total > 100 THEN 'Large'
    ELSE 'Unknown'
  END AS property_size
FROM property_details; """

conn_sql2 =  pd.DataFrame(engine.connect().execute(text(problem_2)))
conn_sql2

,id,start_date,end_date,created_on,lat,lon,l1,l2,l3,rooms,bedrooms,bathrooms,surface_total,surface_covered,property_size
0,5Be4XjP4b1Olk02vXOHLqA==,2020-07-31,2020-08-28,2020-07-31,-34.557563,-58.442389,Argentina,Capital Federal,Belgrano,4.0,3.0,4.0,155.0,150.0,Large
1,V+6946R1DSniL3DToznOBw==,2020-12-16,2020-12-17,2020-12-16,-34.602959,-58.462030,Argentina,Capital Federal,Paternal,4.0,3.0,3.0,181.0,181.0,Large
2,w0i2gQ7n18T4QYlI3gHjtg==,2021-01-05,9999-12-31,2021-01-05,-34.579070,-58.403829,Argentina,Capital Federal,Palermo,4.0,2.0,2.0,230.0,211.0,Large
3,+FVdVVYFmNvza0tOpXfi/A==,2020-06-04,2020-06-25,2020-06-04,-34.797896,-58.385961,Argentina,Bs.As. G.B.A. Zona Sur,Almirante Brown,3.0,2.0,2.0,70.0,65.0,Medium
4,Fg4t539n8vLsWIEQbZ4yPw==,2020-10-22,2020-10-31,2020-10-22,-34.599525,-58.403537,Argentina,Capital Federal,Balvanera,1.0,1.0,1.0,40.0,36.0,Small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43431,RmXNws2019JAidTqtzJy2w==,2020-06-08,2020-06-08,2020-06-08,-34.435111,-58.561232,Argentina,Bs.As. G.B.A. Zona Norte,San Fernando,3.0,2.0,1.0,61.0,56.0,Medium
43432,JpnJWzch98h+je5JL+ZR0Q==,2020-06-02,2020-06-25,2020-06-02,-34.404181,-58.648389,Argentina,Bs.As. G.B.A. Zona Norte,Tigre,3.0,2.0,2.0,80.0,80.0,Medium
43433,NDC8YYYk9XKMzAfc72yVCw==,2020-08-11,2020-08-13,2020-08-11,-34.552139,-58.469208,Argentina,Capital Federal,Nuñez,2.0,1.0,1.0,50.0,50.0,Medium
43434,mH5Ua+P7GkDCS6AkvAMVjg==,2020-09-15,2020-10-16,2020-09-15,-34.559318,-58.445475,Argentina,Capital Federal,Belgrano,2.0,1.0,2.0,54.0,45.0,Medium
43435,5WGZjySGb/v71THZsSBd0g==,2020-09-01,2020-09-04,2020-09-01,-34.391805,-58.628711,Argentina,Bs.As. G.B.A. Zona Norte,Tigre,9.0,5.0,5.0,500.0,450.0,Large

In [ ]:
# question 3 : List all properties (id) in the "Belgrano" neighborhood (l3) that have the same number of bedrooms and bathrooms as another property in the dataset:


problem_3 = """select p1.id,p1.l3,p1.bedrooms,p2.bedrooms,p1.bathrooms,p2.bathrooms from property_details p1 inner join property_details p2
on p1.id = p2.id and p1.bathrooms = p2.bathrooms and p1.bedrooms = p2.bedrooms
where p1.l3 = 'Belgrano' and p2.l3 = 'Belgrano' """

conn_sql3 =  pd.DataFrame(engine.connect().execute(text(problem_3)))

conn_sql3

,id,l3,bedrooms,bedrooms,bathrooms,bathrooms
0,5Be4XjP4b1Olk02vXOHLqA==,Belgrano,3.0,3.0,4.0,4.0
1,F+GF0xxgEoQ8FHaSUbPxfQ==,Belgrano,3.0,3.0,2.0,2.0
2,3l0RfMrJh4v53riOmSUgVQ==,Belgrano,2.0,2.0,2.0,2.0
3,kU5f32VoLFhgCXHoj42S/A==,Belgrano,4.0,4.0,2.0,2.0
4,I5Qis31CnRAmOOYrS28M/Q==,Belgrano,3.0,3.0,3.0,3.0
...,...,...,...,...,...,...
2321,6YlEW++cof1VIYq2VwrNDw==,Belgrano,1.0,1.0,1.0,1.0
2322,uOWYd9pNtIVEkIIZD/VuQg==,Belgrano,3.0,3.0,2.0,2.0
2323,Ci6LpIjLs5ZS0f0A7uRrKA==,Belgrano,2.0,2.0,2.0,2.0
2324,IVvpfKrIFdSgaQwbiNjPlA==,Belgrano,4.0,4.0,4.0,4.0
2325,mH5Ua+P7GkDCS6AkvAMVjg==,Belgrano,1.0,1.0,2.0,2.0

In [ ]:
# question 4 : Calculate the average price per square meter (price / surface_total) for each property type (property_type) in
#the "Belgrano" neighborhood (l3)

problem_4  = """select (b.price/a.surface_total)as price_per_square_meter,b.property_type,a.l3 from property_details a
join property_price_details b on a.id = b.id where a.l3 = 'Belgrano' group by b.property_type """

conn_sql4 =  pd.DataFrame(engine.connect().execute(text(problem_4)))

conn_sql4

   price_per_square_meter    property_type        l3
0             4900.000000             Casa  Belgrano
1             1258.064516     Departamento  Belgrano
2             1043.478261  Local comercial  Belgrano
3             1323.987539             Lote  Belgrano
4              997.500000          Oficina  Belgrano
5             1692.307692               PH  Belgrano

In [ ]:
# question 5: Calculate the cumulative price for each property type, ordered by the creation date
problem_5 = """SELECT
    pd.id ,
    ppd.property_type,
    pd.created_on,
    ppd.price,
    SUM(ppd.price) OVER (PARTITION BY ppd.property_type ORDER BY pd.created_on) AS cumulative_price
FROM Property_Details pd
INNER JOIN Property_Price_Details ppd ON pd.id = ppd.id
ORDER BY ppd.property_type, pd.created_on;
 """

conn_sql5 =  pd.DataFrame(engine.connect().execute(text(problem_5)))
conn_sql5

,id,property_type,created_on,price,cumulative_price
0,5NR2RTibJiNxOw8l8wDNLg==,Casa,2020-01-08,75000.0,75000.0
1,t3OI2u6STkNtVGNdq9jcvQ==,Casa,2020-01-16,45000.0,1313000.0
2,2rj+1L8JK+WKfD2h63RYow==,Casa,2020-01-16,50000.0,1313000.0
3,IIkq+B1HObgm+N1FpCFCKQ==,Casa,2020-01-16,180000.0,1313000.0
4,phr2jIuvWg8p/XBlTx0sGQ==,Casa,2020-01-16,65000.0,1313000.0
...,...,...,...,...,...
43431,mRoaYQMEWDLt//8UM6NT7g==,PH,2021-01-14,230000.0,404762831.0
43432,i6Zm8wlLuxlcin73WYKqVQ==,PH,2021-01-14,210000.0,404762831.0
43433,t6HB4RcJ74sQKjoUU6vMNg==,PH,2021-01-14,230000.0,404762831.0
43434,Xa9Yduj6/pzhpMS9ya3Esg==,PH,2021-01-14,225000.0,404762831.0
43435,Yz7jdYMbFF+2aQfU9qj7xw==,PH,2021-01-14,35000.0,404762831.0

In [ ]:
#Identify properties that have a higher price than the average price of properties with the same number of bedrooms and bathrooms
problem_6 = """SELECT
    pd.id,
    pd.bedrooms,
    pd.bathrooms,
    ppd.price
FROM
    property_details pd
JOIN
    property_price_details ppd
ON
    pd.id = ppd.id
WHERE
    ppd.price > (
        SELECT
            AVG(ppd2.price)
        FROM
            property_details pd2
        JOIN
            property_price_details ppd2
        ON
            pd2.id = ppd2.id
        WHERE
            pd2.bedrooms = pd.bedrooms
        AND
            pd2.bathrooms = pd.bathrooms
    ); """

conn_sql6 = pd.DataFrame(engine.connect().execute(text(problem_6)))
conn_sql6

                            id  bedrooms  bathrooms      price
0     eHozoAsySh4plT4G4o7ZAw==       1.0        1.0   360000.0
1     F+GF0xxgEoQ8FHaSUbPxfQ==       3.0        2.0  1300000.0
2     kA1uUfkh5e8aF9aCVzUbrA==       4.0        3.0  1250000.0
3     c60eO1esSQFLM2X1vQaXlg==       1.0        1.0   262000.0
4     3pYYkhTe9FQbflza7C9EnQ==       1.0        1.0  8228766.0
...                        ...       ...        ...        ...
5612  BMLHzNKa2cVeW4hFlfnWZA==       3.0        2.0  1250000.0
5613  rsHV3kgjk+gtmkSb32Hojg==       3.0        2.0   670000.0
5614  MCvEFrFlEokMZcORqsoOCQ==       3.0        1.0   320000.0
5615  T7V27J16Y1S6gGu58u3JIw==       4.0        2.0   310000.0
5616  5WGZjySGb/v71THZsSBd0g==       5.0        5.0  1200000.0

[5617 rows x 4 columns]

In [ ]:
# question 7 : Identify the 10 locations (l3) with the highest total surface area (sum of surface_total) of properties listed for
#sale (operation_type = 'Venta'):

problem_7 = """SELECT pd.l3, SUM(pd.surface_total) AS total_surface_area
FROM Property_Details pd
INNER JOIN Property_Price_Details ppd ON pd.id = ppd.id
WHERE ppd.operation_type = 'Venta'
GROUP BY pd.l3
ORDER BY total_surface_area DESC
LIMIT 10; """

conn_sql7 = pd.DataFrame(engine.connect().execute(text(problem_7)))
conn_sql7

              l3  total_surface_area
0          Tigre            454465.0
1        Rosario            331595.0
2        Palermo            249909.0
3          Pilar            214308.0
4       Belgrano            213462.0
5     San Isidro            175462.0
6  Villa Urquiza            171980.0
7       La Plata            168131.0
8  Vicente López            145303.0
9        Escobar            138415.0

In [ ]:
# question 8 : Find the top 5 most expensive properties (based on price) in the "Palermo" neighborhood (l3) that were listed
#in August 2020:
problem_8 = """SELECT pd.id , ppd.price, pd.l3, pd.created_on
FROM property_details pd
INNER JOIN property_price_details ppd ON pd.id = ppd.id
WHERE pd.l3 = 'Palermo'
    AND ppd.operation_type = 'Venta'
    AND DATE(pd.created_on) BETWEEN '2020-08-01' AND '2020-08-31'
ORDER BY ppd.price DESC
LIMIT 5;

"""
conn_sql8 = pd.DataFrame(engine.connect().execute(text(problem_8)))
conn_sql8

                         id      price       l3  created_on
0  USMCY74tSt/w7kt5ACB1lQ==  4000000.0  Palermo  2020-08-30
1  dM8I+dJjssyb8HvbbBnCHw==  1980000.0  Palermo  2020-08-11
2  KXKexQ3CiqHowcWRBmaxYQ==  1650000.0  Palermo  2020-08-08
3  JbwB3v6R0C4rW97pcK4hIw==  1350000.0  Palermo  2020-08-13
4  nujZFNyu/t93+/ZigbmzLA==  1349000.0  Palermo  2020-08-22

In [ ]:
# question 9 : Find the top 3 properties with the highest price per square meter (price divided by surface area) within each
#property type.

problem_9 = """WITH RankedProperties AS (
    SELECT
        pd.id ,
        ppd.property_type,
        ppd.price,
        pd.surface_total,
        pd.surface_covered,
        ROW_NUMBER() OVER (PARTITION BY ppd.property_type ORDER BY ppd.price / pd.surface_total DESC) AS rn
    FROM Property_Details pd
    INNER JOIN Property_Price_Details ppd ON pd.id = ppd.id
    WHERE pd.surface_total > 0
)
SELECT id, property_type, price, surface_total, surface_covered
FROM RankedProperties
WHERE rn <= 3;
"""
conn_sql9 =  pd.DataFrame(engine.connect().execute(text(problem_9)))
conn_sql9

,id,property_type,price,surface_total,surface_covered
0,4uEUcuIO6yA9ZD4PBAXjVw==,Casa,36400000.0,131.0,116.0
1,PowAluD2jcoKjBuOE8eALw==,Casa,22809690.0,115.0,75.0
2,ujrbSEDO6JqQ3boPSGuc2A==,Casa,13600000.0,70.0,57.0
3,L/hHlfmnL44avxcBKaEdFA==,Casa de campo,390000.0,1537.0,561.0
4,lkb1/y0lWTtuynnIXk/3vQ==,Casa de campo,399000.0,2540.0,260.0
5,Y/zwWcn7uOycF+zPMv3+0Q==,Casa de campo,67000.0,2934.0,80.0
6,27nCoOot/g4/EZwFNwplUQ==,Cochera,65000.0,52.0,49.0
7,HXIedfxrdJkcwDVkQeRi4Q==,Cochera,15000.0,71.0,46.0
8,A3oPmqYgyU2m8Keaxn5lRw==,Cochera,14000.0,71.0,46.0
9,shQ41FdOdKIxclSV+DrQ5Q==,Departamento,70550000.0,126.0,100.0
10,n5zv1RZqaB9N3WolYh3Ykw==,Departamento,70550000.0,126.0,126.0
11,OwMu9VcPaYnoEIgs9YOyIQ==,Departamento,27370000.0,56.0,56.0
12,OiwQ+uDzl+q+hwgepGHyoQ==,Depósito,646000.0,485.0,485.0
13,39vyn2i7Em6cbkKwWo5+0w==,Depósito,234600.0,195.0,195.0
14,ccn2TwbQGXgRv98Zy5iCdA==,Depósito,390000.0,415.0,415.0
15,W1NbAi6koEb/7rc6nEAJ1A==,Local comercial,4000000.0,40.0,40.0
16,P2q2sFf8AFO9BF1BTMYv/Q==,Local comercial,3307500.0,50.0,50.0
17,yi1GOH2zOwilimc0SnSeVA==,Local comercial,239000.0,34.0,34.0
18,8+TQSLK+EYUCHOESafJjLw==,Lote,3600000.0,111.0,111.0
19,Byq3NAYNqOsbGAxjMjXr3Q==,Lote,4500000.0,594.0,512.0
20,KEsmsquWHk/w935xHXAbOw==,Lote,3000000.0,588.0,588.0
21,p4QtSeddOXgPGAkWLCvWIA==,Oficina,9019800.0,53.0,49.0
22,G4pkU6hvAcsxnfiPH3qCbA==,Oficina,195000.0,37.0,34.0
23,dq5EfMbfwaAmMKqvAdNO9w==,Oficina,695000.0,150.0,140.0
24,k7QdyTsiPtoytS6KDLTe+A==,Otro,3000000.0,58.0,58.0
25,v5RsVZW4C1X6OGpTUFrA6g==,Otro,6200000.0,200.0,180.0
26,Vk+rUxVm04w0dy0m6fZPTg==,Otro,3652000.0,200.0,150.0
27,S9e+o56oek2yMWFL/byXhg==,PH,7959000.0,60.0,60.0
28,bpw2zhTyKijNBqCL5r17+g==,PH,8293000.0,92.0,92.0
29,lINKrnLl3fwBuoXEciHdsg==,PH,3500000.0,43.0,40.0

In [ ]:
# question 10 : Find the top 3 locations (l1, l2, l3) with the highest average price per square meter (price / surface_total) for
#properties listed for sale (operation_type = 'Venta') in the year 2020. Exclude locations with fewer than 10
#properties listed for sale in 2020 from the results.
problem_10 = """WITH LocationAverages AS (
    SELECT
        pd.l1,
        pd.l2,
        pd.l3,
        AVG(ppd.price / pd.surface_total) AS avg_price_per_sqm,
        COUNT(*) AS property_count
    FROM Property_Details pd
    INNER JOIN Property_Price_Details ppd ON pd.id = ppd.id
    WHERE ppd.operation_type = 'Venta'
      AND DATE(pd.created_on) BETWEEN '2020-08-01' AND '2020-08-31'
    GROUP BY pd.l1, pd.l2, pd.l3
    HAVING COUNT(*) >= 10
),
RankedLocations AS (
    SELECT
        l1,
        l2,
        l3,
        avg_price_per_sqm,
        ROW_NUMBER() OVER (ORDER BY avg_price_per_sqm DESC) AS rn
    FROM LocationAverages
)
SELECT l1, l2, l3, avg_price_per_sqm
FROM RankedLocations
WHERE rn <= 3;
"""
conn_sql10 =  pd.DataFrame(engine.connect().execute(text(problem_10)))
conn_sql10

          l1               l2             l3  avg_price_per_sqm
0  Argentina  Capital Federal  San Cristobal       49221.589993
1  Argentina         Santa Fe    San Lorenzo       42623.601795
2  Argentina         Santa Fe        Rosario       41448.756851

SECTION_3 : ** Expose the results in API **

In [ ]:
!apt-get install wget

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
wget is already the newest version (1.21.2-2ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 18 not upgraded.

In [ ]:
# downloading the file
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz

--2023-09-24 13:00:48--  https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz
Resolving bin.equinox.io (bin.equinox.io)... 54.161.241.46, 52.202.168.65, 18.205.222.128, ...
Connecting to bin.equinox.io (bin.equinox.io)|54.161.241.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13856790 (13M) [application/octet-stream]
Saving to: ‘ngrok-stable-linux-amd64.tgz’

ngrok-stable-linux- 100%[===================>]  13.21M  5.96MB/s    in 2.2s

2023-09-24 13:00:51 (5.96 MB/s) - ‘ngrok-stable-linux-amd64.tgz’ saved [13856790/13856790]

In [ ]:
# extracting the file
!tar -xvf /content/ngrok-stable-linux-amd64.tgz

ngrok

In [ ]:
from flask import Flask,jsonify
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app)

Creating API endpoints for the 10 questions in Section 2 and print the results as the API response

In [ ]:
@app.route('/question-1', methods=['GET'])
def question_1():
    connect = sqlite3.connect("Housing_data.db")
    problem_1 ="SELECT pd.id, ppd.property_type, pd.l1, ppd.price FROM property_details pd INNER JOIN property_price_details ppd ON pd.id = ppd.id WHERE pd.l1 = 'Estados Unidos' AND ppd.price > 1000000;"
    conn_sql1 = pd.DataFrame(engine.connect().execute(text(problem_1)))
    dictionary_1 =conn_sql1.to_dict(orient="records" )
    return jsonify(dictionary_1)

In [ ]:
@app.route('/question-2', methods=['GET'])
def question_2():
    connect = sqlite3.connect("Housing_data.db")
    problem_2 = """SELECT *,CASE WHEN surface_total < 50 THEN 'Small' WHEN surface_total >= 50 AND surface_total <= 100 THEN 'Medium' WHEN surface_total > 100 THEN 'Large' ELSE 'Unknown' END AS property_sizeFROM property_details; """
    conn_sql2 =  pd.DataFrame(engine.connect().execute(text(problem_2)))
    dictionary_2 =conn_sql2.to_dict(orient="records" )
    return jsonify(dictionary_2)

In [ ]:
@app.route('/que3', methods=['GET']) # NOTE : This cell route is que3 which is different from other cells just because its throwing an error so changed the name
def que3():
    connect = sqlite3.connect("Housing_data.db")
    problem_3 = """select p1.id,p1.l3,p1.bedrooms,p2.bedrooms,p1.bathrooms,p2.bathrooms from property_details p1 inner join property_details p2 on p1.id = p2.id and p1.bathrooms = p2.bathrooms and p1.bedrooms = p2.bedrooms where p1.l3 = 'Belgrano' and p2.l3 = 'Belgrano' """

    conn_sql3 =  pd.DataFrame(engine.connect().execute(text(problem_3)))
    dictionary_3 =conn_sql3.to_dict(orient="records" )
    return jsonify(dictionary_3)

In [ ]:
@app.route('/question-4', methods=['GET'])
def question_4():
    connect = sqlite3.connect("Housing_data.db")
    problem_4  = """select (b.price/a.surface_total)as price_per_square_meter,b.property_type,a.l3 from property_details a
     join property_price_details b on a.id = b.id where a.l3 = 'Belgrano' group by b.property_type """
    conn_sql4 =  pd.DataFrame(engine.connect().execute(text(problem_4)))
    dictionary_4 =conn_sql4.to_dict(orient="records" )
    return jsonify(dictionary_4)

In [ ]:
@app.route('/question-5', methods=['GET'])
def question_5():
    connect = sqlite3.connect("Housing_data.db")
    problem_5 = """SELECT
    pd.id ,
    ppd.property_type,
    pd.created_on,
    ppd.price,
    SUM(ppd.price) OVER (PARTITION BY ppd.property_type ORDER BY pd.created_on) AS cumulative_price
    FROM Property_Details pd
    INNER JOIN Property_Price_Details ppd ON pd.id = ppd.id
    ORDER BY ppd.property_type, pd.created_on;"""
    conn_sql5 =  pd.DataFrame(engine.connect().execute(text(problem_5)))
    dictionary_5 =conn_sql5.to_dict(orient="records" )
    return jsonify(dictionary_5)

In [ ]:
@app.route('/question-6', methods=['GET'])
def question_6():
    connect = sqlite3.connect("Housing_data.db")
    problem_6 = """SELECT pd.id,pd.bedrooms,pd.bathrooms,ppd.price FROM property_details pd JOIN property_price_details ppd ON pd.id = ppd.id WHERE
    ppd.price > (
        SELECT
            AVG(ppd2.price)
        FROM
            property_details pd2
        JOIN
            property_price_details ppd2
        ON
            pd2.id = ppd2.id
        WHERE
            pd2.bedrooms = pd.bedrooms
        AND
            pd2.bathrooms = pd.bathrooms ); """

    conn_sql6 = pd.DataFrame(engine.connect().execute(text(problem_6)))
    dictionary_6 =conn_sql6.to_dict(orient="records" )
    return jsonify(dictionary_6)

In [ ]:
@app.route('/question-7', methods=['GET'])
def question_7():
    connect = sqlite3.connect("Housing_data.db")
    problem_7 = """SELECT pd.l3, SUM(pd.surface_total) AS total_surface_area
    FROM Property_Details pd
    INNER JOIN Property_Price_Details ppd ON pd.id = ppd.id
    WHERE ppd.operation_type = 'Venta'
    GROUP BY pd.l3
    ORDER BY total_surface_area DESC
    LIMIT 10; """

    conn_sql7 = pd.DataFrame(engine.connect().execute(text(problem_7)))
    dictionary_7 =conn_sql7.to_dict(orient="records" )
    return jsonify(dictionary_7)

In [ ]:
@app.route('/question-8', methods=['GET'])
def question_8():
    connect = sqlite3.connect("Housing_data.db")
    problem_8 = """SELECT pd.id , ppd.price, pd.l3, pd.created_on
       FROM property_details pd
       INNER JOIN property_price_details ppd ON pd.id = ppd.id
    WHERE pd.l3 = 'Palermo'
    AND ppd.operation_type = 'Venta'
    AND DATE(pd.created_on) BETWEEN '2020-08-01' AND '2020-08-31'
    ORDER BY ppd.price DESC
     LIMIT 5; """
    conn_sql8 = pd.DataFrame(engine.connect().execute(text(problem_8)))
    dictionary_8 =conn_sql8.to_dict(orient="records" )
    return jsonify(dictionary_8)

In [ ]:
@app.route('/question-9', methods=['GET'])
def question_9():
    connect = sqlite3.connect("Housing_data.db")
    problem_9 = """WITH RankedProperties AS (
    SELECT
        pd.id ,
        ppd.property_type,
        ppd.price,
        pd.surface_total,
        pd.surface_covered,
        ROW_NUMBER() OVER (PARTITION BY ppd.property_type ORDER BY ppd.price / pd.surface_total DESC) AS rn
    FROM Property_Details pd
    INNER JOIN Property_Price_Details ppd ON pd.id = ppd.id
    WHERE pd.surface_total > 0) SELECT id, property_type, price, surface_total, surface_covered FROM RankedProperties WHERE rn <= 3; """
    conn_sql9 =  pd.DataFrame(engine.connect().execute(text(problem_9)))
    dictionary_9 =conn_sql9.to_dict(orient="records" )
    return jsonify(dictionary_9)

In [ ]:
@app.route('/question-10', methods=['GET'])
def question_10():
    connect = sqlite3.connect("Housing_data.db")
    problem_10 = """WITH LocationAverages AS (
    SELECT
        pd.l1,
        pd.l2,
        pd.l3,
        AVG(ppd.price / pd.surface_total) AS avg_price_per_sqm,
        COUNT(*) AS property_count
    FROM Property_Details pd
    INNER JOIN Property_Price_Details ppd ON pd.id = ppd.id
    WHERE ppd.operation_type = 'Venta'
      AND DATE(pd.created_on) BETWEEN '2020-08-01' AND '2020-08-31'
    GROUP BY pd.l1, pd.l2, pd.l3
    HAVING COUNT(*) >= 10),RankedLocations AS (
    SELECT
        l1,
        l2,
        l3,
        avg_price_per_sqm,
        ROW_NUMBER() OVER (ORDER BY avg_price_per_sqm DESC) AS rn
    FROM LocationAverages) SELECT l1, l2, l3, avg_price_per_sqm FROM RankedLocations WHERE rn <= 3; """
    conn_sql10 =  pd.DataFrame(engine.connect().execute(text(problem_10)))
    dictionary_10 =conn_sql10.to_dict(orient="records" )
    return jsonify(dictionary_10)

In [ ]:
@app.errorhandler(404)  # Creating exception handling error
def not_found(e):
  return jsonify({'data': 'Oops: Resource not found'})

In [ ]:
if __name__ == "__main__":
  app.run() # this is too run the app